"""reconcile schema with models (drop blank_type, nullable duration_expected)

Revision ID: 0ce07b098b48
Revises: 9260b605903f
Create Date: 2026-07-06 23:11:03.890172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ce07b098b48'
down_revision: Union[str, Sequence[str], None] = '9260b605903f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'duration_expected',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('sentence_template_assets', 'blank_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence_template_assets', sa.Column('blank_type', postgresql.ENUM('noun', 'verb', 'adjective', name='word_type'), autoincrement=False, nullable=False))
    op.alter_column('exercises', 'duration_expected',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
