"""rework AssessmentResult for doctor-entered baseline scores

Revision ID: 19516c4e09eb
Revises: 4542356211f9
Create Date: 2026-07-04 10:35:04.900850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19516c4e09eb'
down_revision: Union[str, Sequence[str], None] = '4542356211f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_results', sa.Column('accuracy_score', sa.Float(), nullable=True))
    op.add_column('assessment_results', sa.Column('completion_score', sa.Float(), nullable=True))
    op.drop_column('assessment_results', 'sentence_score')
    op.drop_column('assessment_results', 'command_score')
    op.drop_column('assessment_results', 'total_score')
    op.drop_column('assessment_results', 'naming_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_results', sa.Column('naming_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessment_results', sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessment_results', sa.Column('command_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessment_results', sa.Column('sentence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('assessment_results', 'completion_score')
    op.drop_column('assessment_results', 'accuracy_score')
    # ### end Alembic commands ###
