"""add logic_sequence tables (sequences, sequence_steps, logic_sequence_exercises)

Revision ID: 34902a5a5257
Revises: bc586af02219
Create Date: 2026-07-15 23:26:31.060482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34902a5a5257'
down_revision: Union[str, Sequence[str], None] = 'bc586af02219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sequence_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id')
    )
    op.create_table('logic_sequence_exercises',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exercise_code', sa.String(length=50), nullable=False),
    sa.Column('exercise_type', sa.String(length=30), server_default=sa.text("'logic_sequence'"), nullable=False),
    sa.Column('target_sequence_id', sa.UUID(), nullable=False),
    sa.Column('suitable_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['target_sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_code')
    )
    op.create_table('sequence_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sequence_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', 'step_order', name='uq_sequence_step_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence_steps')
    op.drop_table('logic_sequence_exercises')
    op.drop_table('sequences')
    # ### end Alembic commands ###
