"""make therapy_plan therapist_id nullable

Revision ID: 4542356211f9
Revises: a82ebc62b7b5
Create Date: 2026-07-03 19:21:41.389810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4542356211f9'
down_revision: Union[str, Sequence[str], None] = 'a82ebc62b7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapy_plans', 'therapist_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapy_plans', 'therapist_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
