"""add topic_progress table

Revision ID: 9260b605903f
Revises: 19516c4e09eb
Create Date: 2026-07-05 01:45:19.759890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9260b605903f'
down_revision: Union[str, Sequence[str], None] = '19516c4e09eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ĐÃ CHỈNH TAY: cột topic dùng ENUM 'topic' CÓ SẴN trong DB (tạo từ migration trước) —
    # create_type=False để không CREATE TYPE trùng (autogenerate mặc định sẽ fail ở đây).
    op.create_table('topic_progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('topic', postgresql.ENUM('daily_activity', 'food_drink', 'household_item', 'family', 'body_part', 'number', name='topic', create_type=False), nullable=False),
    sa.Column('current_level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('consecutive_high_scores', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_level BETWEEN 1 AND 3', name='ck_topic_progress_level'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'topic', name='uq_topic_progress_patient_topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_progress')
    # ### end Alembic commands ###
