"""add hospital and referring doctor to patient

Revision ID: a82ebc62b7b5
Revises: c6e6e81d96c7
Create Date: 2026-07-03 18:48:21.333966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82ebc62b7b5'
down_revision: Union[str, Sequence[str], None] = 'c6e6e81d96c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('hospital_name', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('referring_doctor_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'referring_doctor_name')
    op.drop_column('patients', 'hospital_name')
    # ### end Alembic commands ###
