"""add therapy_sessions (rule.md session layer) + nullable link on exercise_sessions

Revision ID: bc586af02219
Revises: e80ba5e6b3d5
Create Date: 2026-07-15 12:48:04.467547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc586af02219'
down_revision: Union[str, Sequence[str], None] = 'e80ba5e6b3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapy_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=30), nullable=True),
    sa.Column('vocab_level', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=20), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('planned_count', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('completed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exercise_sessions', sa.Column('therapy_session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exercise_sessions', 'therapy_sessions', ['therapy_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_sessions', type_='foreignkey')
    op.drop_column('exercise_sessions', 'therapy_session_id')
    op.drop_table('therapy_sessions')
    # ### end Alembic commands ###
