"""logic_sequence GD2: nullable assignment_id + logic_sequence_exercise_id on exercise_sessions

Revision ID: c6237f7506db
Revises: 34902a5a5257
Create Date: 2026-07-15 23:59:03.053687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6237f7506db'
down_revision: Union[str, Sequence[str], None] = '34902a5a5257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_sessions', sa.Column('logic_sequence_exercise_id', sa.UUID(), nullable=True))
    op.alter_column('exercise_sessions', 'assignment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'exercise_sessions', 'logic_sequence_exercises', ['logic_sequence_exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_sessions', type_='foreignkey')
    op.alter_column('exercise_sessions', 'assignment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('exercise_sessions', 'logic_sequence_exercise_id')
    # ### end Alembic commands ###
