"""add vocab_level to vocabulary_assets

Revision ID: c6e6e81d96c7
Revises: 1f10c6a2eef2
Create Date: 2026-07-02 20:02:47.450625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e6e81d96c7'
down_revision: Union[str, Sequence[str], None] = '1f10c6a2eef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary_assets', sa.Column('vocab_level', sa.Integer(), nullable=False))
    op.create_check_constraint('ck_vocabulary_vocab_level', 'vocabulary_assets', 'vocab_level BETWEEN 1 AND 3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_vocabulary_vocab_level', 'vocabulary_assets', type_='check')
    op.drop_column('vocabulary_assets', 'vocab_level')
    # ### end Alembic commands ###
