"""add color_recognition tables + nullable link on exercise_sessions

Revision ID: dea60d48edf0
Revises: c6237f7506db
Create Date: 2026-07-16 00:45:15.635755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dea60d48edf0'
down_revision: Union[str, Sequence[str], None] = 'c6237f7506db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('color_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hex_code', sa.String(length=9), nullable=False),
    sa.Column('image_file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color_id')
    )
    op.create_table('color_recognition_exercises',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exercise_code', sa.String(length=50), nullable=False),
    sa.Column('exercise_type', sa.String(length=30), server_default=sa.text("'color_recognition'"), nullable=False),
    sa.Column('target_color_id', sa.UUID(), nullable=False),
    sa.Column('instruction_audio', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('suitable_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['target_color_id'], ['colors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_code')
    )
    op.add_column('exercise_sessions', sa.Column('color_recognition_exercise_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exercise_sessions', 'color_recognition_exercises', ['color_recognition_exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_sessions', type_='foreignkey')
    op.drop_column('exercise_sessions', 'color_recognition_exercise_id')
    op.drop_table('color_recognition_exercises')
    op.drop_table('colors')
    # ### end Alembic commands ###
