"""nullable audio fields, fix cmd exercise target constraint

Revision ID: 1f10c6a2eef2
Revises: 3487ebb6ab7f
Create Date: 2026-07-02 19:03:36.665734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1f10c6a2eef2'
down_revision: Union[str, Sequence[str], None] = '3487ebb6ab7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_assets', sa.Column('command_text', sa.String(length=500), nullable=False))
    op.add_column('command_assets', sa.Column('command_audio_file', sa.String(length=255), nullable=True))
    op.alter_column('command_assets', 'distractor_vocab_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('command_assets', 'audio_file')
    op.add_column('exercises', sa.Column('target_command_id', sa.UUID(), nullable=True))
    op.execute('ALTER TABLE exercises DROP CONSTRAINT IF EXISTS ck_exercise_target_exclusivity')
    op.create_check_constraint(
        'ck_exercise_target_exclusivity',
        'exercises',
        "(exercise_type = 'naming' AND target_vocab_id IS NOT NULL AND target_command_id IS NULL"
        " AND target_sentence_instance_id IS NULL) OR (exercise_type = 'command_identification'"
        " AND target_vocab_id IS NOT NULL AND target_command_id IS NULL"
        " AND target_sentence_instance_id IS NULL) OR (exercise_type = 'sentence_building'"
        " AND target_sentence_instance_id IS NOT NULL AND target_vocab_id IS NULL"
        " AND target_command_id IS NULL)"
    )
    op.create_foreign_key(None, 'exercises', 'command_assets', ['target_command_id'], ['id'])
    op.alter_column('sentence_instance_assets', 'audio_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentence_instance_assets', 'audio_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_constraint('ck_exercise_target_exclusivity', 'exercises', type_='check')
    op.create_check_constraint(
        'ck_exercise_target_exclusivity',
        'exercises',
        "(exercise_type = 'naming' AND target_vocab_id IS NOT NULL AND target_command_id IS NULL"
        " AND target_sentence_instance_id IS NULL) OR (exercise_type = 'command_identification'"
        " AND target_command_id IS NOT NULL AND target_vocab_id IS NULL"
        " AND target_sentence_instance_id IS NULL) OR (exercise_type = 'sentence_building'"
        " AND target_sentence_instance_id IS NOT NULL AND target_vocab_id IS NULL"
        " AND target_command_id IS NULL)"
    )
    op.drop_column('exercises', 'target_command_id')
    op.alter_column('command_assets', 'distractor_vocab_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('command_assets', sa.Column('audio_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('command_assets', 'command_audio_file')
    op.drop_column('command_assets', 'command_text')
    # ### end Alembic commands ###
