"""initial schema

Revision ID: 3487ebb6ab7f
Revises: 
Create Date: 2026-07-01 22:56:24.840122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3487ebb6ab7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgcrypto cần cho gen_random_uuid() trên PostgreSQL < 13.
    # PostgreSQL 13+ có sẵn trong core, câu lệnh này vẫn an toàn để giữ.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_template_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template', sa.String(length=255), nullable=False),
    sa.Column('blank_type', sa.Enum('noun', 'verb', 'adjective', name='word_type', create_constraint=True), nullable=False),
    sa.Column('topic_constraint', sa.Enum('daily_activity', 'food_drink', 'household_item', 'family', 'body_part', 'number', name='topic', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('patient', 'therapist', 'caregiver', 'admin', name='user_role', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='user_status', create_constraint=True), server_default='active', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vocabulary_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_word', sa.String(length=255), nullable=False),
    sa.Column('accepted_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted_classifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_file', sa.String(length=255), nullable=True),
    sa.Column('audio_file', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.Enum('daily_activity', 'food_drink', 'household_item', 'family', 'body_part', 'number', name='topic', create_constraint=True), nullable=False),
    sa.Column('word_type', sa.Enum('noun', 'verb', 'adjective', name='word_type', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('audio_file', sa.String(length=255), nullable=False),
    sa.Column('target_vocab_id', sa.UUID(), nullable=False),
    sa.Column('distractor_vocab_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['target_vocab_id'], ['vocabulary_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('reminder', 'alert', 'new_feedback', 'plan_updated', 'system', name='notification_type', create_constraint=True), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', create_constraint=True), nullable=False),
    sa.Column('native_language', sa.String(length=50), server_default='vi', nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('aphasia_type', sa.String(length=100), nullable=True),
    sa.Column('severity_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sentence_instance_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('vocab_id', sa.UUID(), nullable=False),
    sa.Column('full_sentence', sa.String(length=500), nullable=False),
    sa.Column('accepted_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audio_file', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['sentence_template_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('license_no', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('language', 'speech', 'cognitive', 'comprehension', name='assessment_type', create_constraint=True), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'cancelled', name='assessment_status', create_constraint=True), server_default='in_progress', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caregivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relation_to_patient', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exercise_code', sa.String(length=20), nullable=False),
    sa.Column('exercise_type', sa.Enum('naming', 'command_identification', 'sentence_building', name='exercise_type', create_constraint=True), nullable=False),
    sa.Column('mode', sa.Enum('recognition', 'repetition', name='command_mode', create_constraint=True), nullable=True),
    sa.Column('topic', sa.Enum('daily_activity', 'food_drink', 'household_item', 'family', 'body_part', 'number', name='topic', create_constraint=True), nullable=False),
    sa.Column('vocab_level', sa.Integer(), nullable=False),
    sa.Column('suitable_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_vocab_id', sa.UUID(), nullable=True),
    sa.Column('target_command_id', sa.UUID(), nullable=True),
    sa.Column('target_sentence_instance_id', sa.UUID(), nullable=True),
    sa.Column('duration_expected', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(exercise_type = 'naming'  AND target_vocab_id IS NOT NULL  AND target_command_id IS NULL  AND target_sentence_instance_id IS NULL) OR (exercise_type = 'command_identification'  AND target_command_id IS NOT NULL  AND target_vocab_id IS NULL  AND target_sentence_instance_id IS NULL) OR (exercise_type = 'sentence_building'  AND target_sentence_instance_id IS NOT NULL  AND target_vocab_id IS NULL  AND target_command_id IS NULL)", name='ck_exercise_target_exclusivity'),
    sa.CheckConstraint('vocab_level BETWEEN 1 AND 3', name='ck_exercise_vocab_level'),
    sa.ForeignKeyConstraint(['target_command_id'], ['command_assets.id'], ),
    sa.ForeignKeyConstraint(['target_sentence_instance_id'], ['sentence_instance_assets.id'], ),
    sa.ForeignKeyConstraint(['target_vocab_id'], ['vocabulary_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_code')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('progress_summary', 'assessment_report', 'therapy_report', name='report_type', create_constraint=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapy_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'expired', name='plan_status', create_constraint=True), server_default='draft', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('naming_score', sa.Float(), nullable=True),
    sa.Column('command_score', sa.Float(), nullable=True),
    sa.Column('sentence_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('exercise_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['therapy_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'graded', 'cancelled', name='session_status', create_constraint=True), server_default='in_progress', nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['exercise_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.String(length=500), nullable=True),
    sa.Column('selected_vocab_id', sa.UUID(), nullable=True),
    sa.Column('audio_duration_s', sa.Float(), nullable=True),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Enum('pass', 'near', 'retry', 'skip', 'correct', 'incorrect', 'invalid', name='result_label', create_constraint=True), nullable=False),
    sa.Column('used_fallback_audio', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exercise_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speech_recordings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['session_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='vi', nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['speech_recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id')
    )
    op.create_table('aphasia_analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transcription_id', sa.UUID(), nullable=False),
    sa.Column('detected_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcription_id')
    )
    op.create_table('ai_feedbacks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('strengths', sa.String(length=500), nullable=True),
    sa.Column('weaknesses', sa.String(length=500), nullable=True),
    sa.Column('suggestions', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['aphasia_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_feedbacks')
    op.drop_table('aphasia_analyses')
    op.drop_table('transcriptions')
    op.drop_table('speech_recordings')
    op.drop_table('session_results')
    op.drop_table('exercise_sessions')
    op.drop_table('exercise_assignments')
    op.drop_table('assessment_results')
    op.drop_table('therapy_plans')
    op.drop_table('reports')
    op.drop_table('exercises')
    op.drop_table('caregivers')
    op.drop_table('assessments')
    op.drop_table('therapists')
    op.drop_table('sentence_instance_assets')
    op.drop_table('profiles')
    op.drop_table('patients')
    op.drop_table('notifications')
    op.drop_table('command_assets')
    op.drop_table('vocabulary_assets')
    op.drop_table('users')
    op.drop_table('sentence_template_assets')
    # ### end Alembic commands ###
